name: "Lint PR title"

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^(#[A-Z]*-[0-9]* ?){1,}" # Regex the title should match.